### ISSUE TITLE
Pull-Request ??

### ISSUE THREAD

**Issue by davidgm17** [FormacionDgm/API-DailyCRUD#21]
how can I request a pull-request

**Comment by dFarras** [comment]
First go to Pull Request tab on the repository:
![imagen](https://user-images.githubusercontent.com/28202081/44310039-1c697b00-a3d0-11e8-9639-cd7fd185fe00.png)
In there select which branch do you want to merge, and in which branch do you want to merge it:
![imagen](https://user-images.githubusercontent.com/28202081/44310042-33a86880-a3d0-11e8-8bba-3a8a1a0a8ce4.png)
